"""GDS subgraph projections for PageRank E segment (BAE schema v5)."""
from __future__ import annotations

SUBGRAPH_CONFIGS = {
    "mpu": {
        "projection": "mpu_projection",
        "nodes": [
            "mp_References",
            "whu_DataSet",
            "mp_Claim",
            "mp_Statement",
            "mp_Method",
            "mp_Attribution",
            "whu_ScienceEvidence",
            "whu_SupportGraph",
        ],
        "relationships": {
            "MP_SUPPORTS": {"type": "mp_supports", "orientation": "NATURAL"},
            "MP_CHALLENGES": {"type": "mp_challenges", "orientation": "NATURAL"},
            "CITO_ISCITEDBY": {"type": "cito_isCitedBy", "orientation": "NATURAL"},
            "PROV_HADMEMBER": {"type": "prov_hadMember", "orientation": "NATURAL"},
        },
    },
    "ebm": {
        "projection": "ebm_projection",
        "nodes": [
            "whu_EnvironmentFeature",
            "envo_EnvironmentMaterial",
            "whu_SpecimenCollection",
            "whu_SpecimenPreprocessing",
            "whu_ResearchStep",
            "whu_Specimen",
            "whu_ProcessedSpecimen",
            "obi_organism",
            "whu_ChemicalEntity",
            "mp_Method",
            "whu_Device",
            "whu_Reagent",
            "whu_DataSet",
            "iao_DataItem",
            "iao_ScalarMeasurementDatum",
        ],
        "relationships": {
            "WHU_HASCONTEXT": {"type": "whu_hasContext", "orientation": "NATURAL"},
            "WHU_FELLOW": {"type": "whu_fellow", "orientation": "NATURAL"},
            "PROV_WASDERIVEDFROM": {"type": "prov_wasDerivedFrom", "orientation": "NATURAL"},
            "PROV_ATLOCATION": {"type": "prov_atLocation", "orientation": "NATURAL"},
            "WHU_DECLAREDUSED": {"type": "whu_declaredUsed", "orientation": "NATURAL"},
            "WHU_DECLAREDINPUT": {"type": "whu_declaredInput", "orientation": "NATURAL"},
            "WHU_DECLAREDOUTPUT": {"type": "whu_declaredOutput", "orientation": "NATURAL"},
            "P_PLAN_ISPRECEDEDBY": {"type": "p_plan_isPrecededBy", "orientation": "NATURAL"},
            "P_PLAN_ISINPUTVAROF": {"type": "p_plan_isInputVarOf", "orientation": "NATURAL"},
            "P_PLAN_ISOUTPUTVAROF": {"type": "p_plan_isOutputVarOf", "orientation": "NATURAL"},
            "BFO_HAS_PART": {"type": "bfo_has_part", "orientation": "NATURAL"},
            "DCTERMS_HASPART": {"type": "dcterms_hasPart", "orientation": "NATURAL"},
            "IAO_IS_ABOUT": {"type": "iao_is_about", "orientation": "NATURAL"},
        },
    },
    "eem": {
        "projection": "eem_projection",
        "nodes": [
            "whu_BioChemical_Experiment",
            "whu_Computational_Experiment",
            "whu_ResearchStep",
            "whu_Goal",
            "whu_TargetVariable",
            "whu_DataSet",
            "whu_ProcessedSpecimen",
            "whu_Specimen",
            "mp_Method",
            "whu_Device",
            "whu_Reagent",
            "whu_Software",
            "iao_DataItem",
            "iao_ScalarMeasurementDatum",
            "whu_ChemicalEntity",
        ],
        "relationships": {
            "WHU_FELLOW": {"type": "whu_fellow", "orientation": "NATURAL"},
            "WHU_HASGOAL": {"type": "whu_hasGoal", "orientation": "NATURAL"},
            "WHU_HASTARGET": {"type": "whu_hasTarget", "orientation": "NATURAL"},
            "WHU_DECLAREDUSED": {"type": "whu_declaredUsed", "orientation": "NATURAL"},
            "WHU_DECLAREDINPUT": {"type": "whu_declaredInput", "orientation": "NATURAL"},
            "WHU_DECLAREDOUTPUT": {"type": "whu_declaredOutput", "orientation": "NATURAL"},
            "P_PLAN_ISPRECEDEDBY": {"type": "p_plan_isPrecededBy", "orientation": "NATURAL"},
            "P_PLAN_ISINPUTVAROF": {"type": "p_plan_isInputVarOf", "orientation": "NATURAL"},
            "P_PLAN_ISOUTPUTVAROF": {"type": "p_plan_isOutputVarOf", "orientation": "NATURAL"},
            "IAO_IS_ABOUT": {"type": "iao_is_about", "orientation": "NATURAL"},
            "DCTERMS_HASPART": {"type": "dcterms_hasPart", "orientation": "NATURAL"},
        },
    },
}
